### ISSUE TITLE
States vs Composites

### ISSUE THREAD

**Issue by jake-knerr** [jake-knerr/chess#83]
States are for BOTH configuration setting applied to a component AND for styles that change during runtime.  In other more simple terms, a state is for anything that may vary either when created or changing due to user interaction. 

They both use !important. Why? Because if they did not then a composite could override more than expected. 

```css
.button {}
.button--selected {color: red;}

.toggle-button.button {color: purple} // overrides --selected state
```

When I image a composite's behavior, it just overrides exactly what I define and nothing more. 

So why ever use a composite? Composite is defined externally from the super component in a new file. This can be useful when creating a javascript-based component or when creating new components based on a library. However, component hierarchies can be brittle just like class hierarchies because of single-component inheritance.  Multiple inheritance is not viable because of style-conflict specificity uncertainty.
