### ISSUE TITLE
globals

### ISSUE THREAD

**Issue by jake-knerr** [jake-knerr/chess#91]
ok to create component like globals. As long as specificity is 1.

```css
table {
  border-collapse: collapse;
  font-size: 0.875rem;
  table-layout: fixed;
  width: 100%;

  :where(thead) {
    font-weight: bold;

    :where(tr) {
      border-bottom: 2px solid #fff;
    }

    :where(td) {
      padding: 0;
      padding-bottom: 0.5rem;
    }
  }

  :where(tbody) {
    &::before {
      content: "";
      display: block;
      height: 0.5rem;
    }

    :where(button) {
      padding: 0.125rem 0.25rem;
      line-height: normal;
      min-height: auto;
    }

    :where(tr:nth-child(odd)) {
      background: #333;
    }
  }

  :where(tr) {
    > :where(td:first-child) {
      padding-left: 0.25rem;
    }

    > :where(td:last-child) {
      padding-right: 0;
    }
  }

  :where(td) {
    overflow: hidden;
    text-overflow: ellipsis;
    vertical-align: baseline;
    white-space: nowrap;

    > svg {
      height: 24px;
    }

    > img {
      height: 24px;
    }
  }

  :where([data-format="overflow-text"]) {
    text-overflow: unset;
    white-space: normal;
  }
}
```
